kaucu/urls.py
from django.urls import path, include

from kaucu import views
from django.contrib.auth import views as auth_views


user_patterns = ([
    path('', views.UserList.as_view() , name='list'),
    path('<str:slug>/', views.UserDetail.as_view() , name='detail'),
    path('<str:slug>/update', views.UserUpdate.as_view() , name='update'),
    path('<str:slug>/delete', views.UserDelete.as_view() , name='delete'),
    path('create_user', views.UserCreate.as_view() , name='create'),
], 'user')

contact_patterns = ([
    path('', views.ContactList.as_view() , name='list'),
    path('<str:slug>/', views.ContactDetail.as_view() , name='detail'),
    path('<str:slug>/update', views.ContactUpdate.as_view() , name='update'),
    path('<str:slug>/delete', views.ContactDelete.as_view() , name='delete'),
    path('create_contact', views.ContactCreate.as_view() , name='create'),
    path('search/<str:query>', views.ContactSearch.search , name='search'),
], 'contact')

package_patterns = ([
  path('create_package', views.PackageCreate.as_view() , name='create'),
  path('', views.PackageList.as_view() , name='list'),
  path('<int:pk>/', views.PackageDetail.as_view() , name='detail'),
  path('<int:pk>/update', views.PackageUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.PackageDelete.as_view() , name='delete'),
], 'package')

sale_patterns = ([
  path('', views.SaleList.as_view() , name='list'),
  path('<str:slug>/', views.SaleDetail.as_view() , name='detail'),
  path('<str:slug>/payment', views.SaleDetail.as_view() , name='payment'),
  path('<str:slug>/passenger', views.SaleDetail.as_view() , name='passenger'),
  path('<str:slug>/activity', views.SaleDetail.as_view() , name='activity'),

  path('<str:slug>/update', views.SaleUpdate.as_view() , name='update'),
  path('<str:slug>/delete', views.SaleDelete.as_view() , name='delete'),
  path('<str:slug>/create', views.SaleCreate.as_view() , name='create'),
  path('create', views.SaleCreate.as_view() , name='create'),

], 'sale')

hotel_patterns = ([
  path('<str:slug>/create', views.HotelCreate.as_view() , name='create'),
  path('<int:pk>/update', views.HotelUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.HotelDelete.as_view() , name='delete'),
], 'hotel')

flight_patterns = ([
  path('<str:slug>/create', views.FlightCreate.as_view() , name='create'),
  path('<int:pk>/update', views.FlightUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.FlightDelete.as_view() , name='delete'),
], 'flight')

transfer_patterns = ([
  path('<str:slug>/create', views.TransferCreate.as_view() , name='create'),
  path('<int:pk>/update', views.TransferUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.TransferDelete.as_view() , name='delete'),
], 'transfer')


passenger_patterns = ([
  path('<int:pk>/', views.PassengerDelete.as_view() , name='detail'),
  path('<str:slug>/create', views.PassengerCreate.as_view() , name='create'),
  path('<int:pk>/update', views.PassengerUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.PassengerDelete.as_view() , name='delete'),
], 'passenger')


payment_patterns = ([
    path('', views.PaymentList.as_view() , name='list'),
    path('<str:slug>/delete', views.PaymentDelete.as_view() , name='delete'),
    path('create_payment', views.PaymentCreate.as_view() , name='create'),
], 'payment')

sale_payment = ([
    path('<str:slug>/<int:pk>/delete', views.Sale_PaymentDelete.as_view() , name='delete'),
    path('<str:slug>/create', views.Sale_PaymentCreate.as_view() , name='create'),
], 'sale_payment')

supplier_payment = ([
    path('<int:pk>/delete', views.Supplier_PaymentDelete.as_view() , name='delete'),
    path('<int:pk>/create', views.Supplier_PaymentCreate.as_view() , name='create'),
], 'supplier_payment')

supplier_patterns = ([
    path('', views.SupplierList.as_view() , name='list'),
    path('<int:pk>/', views.SupplierDetail.as_view() , name='detail'),
    path('<int:pk>/update', views.SupplierUpdate.as_view() , name='update'),
    path('<int:pk>/delete', views.SupplierDelete.as_view() , name='delete'),
    path('create_supplier', views.SupplierCreate.as_view() , name='create'),
], 'supplier')

responder_patterns = ([
    path('<int:pk>/respond', views.Responder.as_view(), name='respond'),
    path('<str:slug>/respond', views.Responder.as_view(), name='respond'),
    path('<str:path>/redirect', views.ResponderRedirect.as_view(), name='redirect'),
    path('<str:slug>/<str:path>/redirect_slug', views.ResponderRedirectArgs.as_view(), name='redirect_slug'),
    path('<int:pk>/<str:path>/redirect_pk', views.ResponderRedirectArgs.as_view(), name='redirect_pk'),

], 'responder')

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('responder/', include(responder_patterns)),
    path('contact/', include(contact_patterns)),
    path('user/', include(user_patterns)),

    path('package/', include(package_patterns)),
    path('sale/', include(sale_patterns)),
    path('hotel/', include(hotel_patterns)),
    path('flight/', include(flight_patterns)),
    path('transfer/', include(transfer_patterns)),
    path('payment/', include(payment_patterns)),
    path('sale_payment/', include(sale_payment)),
    path('supplier_payment/', include(supplier_payment)),
    path('supplier/', include(supplier_patterns)),

    path('passenger/', include(passenger_patterns)),
]

kaucudjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('kaucu.urls')),
    path('admin/', admin.site.urls),
]

kaucu/models/package.py
from django.db import models
from .user import User

class Package(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_packages')

  package = models.CharField(max_length=100)  
  allow_custom_services = models.BooleanField(default=True)

  def __str__(self):
    return u'{0}'.format(self.package)

kaucu/models/payment.py
from django.db import models
from kaucu.helpers import *
from django.db.models import Sum, F    
from django.db.models.functions import Coalesce
from django import forms
from .user import User
from model_utils import Choices

class PaymentQuerySet(models.QuerySet):
  def prefetch(self):
    return self.prefetch_related('sale_payment_set', 'supplier_payment_set')
  def available_payments(self):
    sum_sale_payment = Sum(Coalesce('sale_payment__amount',0))
    sum_supplier_payment = Sum(Coalesce('supplier_payment__amount',0))
    query = self.prefetch_related('sale_payment_set', 'supplier_payment_set')
    query = query.annotate(sale_total=sum_sale_payment, supplier_total=sum_supplier_payment, available=F('amount')-(F('sale_total')+F('supplier_total')))
    query = query.order_by('-paid_date')
    return query


class Payment(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  slug = models.SlugField(unique=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_payments')

  currency = models.CharField(max_length=3)
  amount = models.DecimalField(default=0, decimal_places=2, max_digits=8)
  paid_date = models.DateField()
  
  DIRECTION = Choices(('IN', 'IN', 'IN'), ('OUT', 'OUT', 'OUT'))
  direction = models.CharField(max_length=5, choices=DIRECTION)
  METHOD = Choices(('Bank Transfer', 'banktransfer', 'Bank Transfer'), ('Cash', 'cash', 'Cash'), ('Cheque', 'cheque', 'Cheque'))
  method = models.CharField(max_length=20, choices=METHOD)

  available = None
  
  objects = PaymentQuerySet.as_manager()

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = "P"+str(Helpers.randomInt(5))
    super().save(*args, **kwargs)
  
  def delete(self, *args, **kwargs):
    #Update status of all sales associated with the payment
    #Get a local copy of salepayments, then delete, as we cannot update status before delete as it wont change
    local_sale_payments = list(self.sale_payment_set.all())
    super().delete(*args, **kwargs)
    for sale_payment in local_sale_payments:
      sale_payment.sale.update_status()

  
  def __str__(self):
    payment = str(self.paid_date)+' Payment '+self.slug+'  '+self.direction
    if self.available:
      payment += ' '+self.currency+' :'+str(self.available)
    return u'{0}'.format(payment)



class PaymentAssignForm(forms.ModelForm):
  amount = forms.DecimalField()
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    payment_queryset =  Payment.objects.available_payments()
    self.fields['payment'] = forms.ModelChoiceField(queryset= payment_queryset.exclude(available=0))
    if 'data' in kwargs:
      available_amount = payment_queryset.get(id=kwargs['data']['payment']).available
      self.fields['amount'] = forms.DecimalField(max_value=available_amount)
      

kaucu/models/sale_payment.py
from django.db import models
from .user import *
from .sale import *
from .payment import *
from .payment_child import *
from django.db.models import Sum, Q

class Sale_Payment(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  sale = models.ForeignKey(Sale, on_delete=models.CASCADE)

  payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
  amount = models.DecimalField(default=0, decimal_places=2, max_digits=8)
  
  objects = PaymentChildQuerySet.as_manager()

  def __str__(self):
    return u'{0}'.format('Sale Payment')
  def save(self, *args, **kwargs):
    super().save(*args, **kwargs)
    self.sale.update_status()

  def delete(self, *args, **kwargs):
    super().delete(*args, **kwargs)
    self.sale.update_status()

kaucu/views/contact.py
from django.urls import reverse

from kaucu.models import  User, Sale
from django.views.generic import *
from kaucu.mixins import *
from django.core import serializers
from django.http import HttpResponse
from django.http import JsonResponse


import django_filters

class ContactFilter(django_filters.FilterSet):
  slug = django_filters.CharFilter(label='ID')
  class Meta:
    model = User
    fields = {'slug': ['exact'], 'email': ['contains'], 'first_name': ['contains'], 'last_name': ['contains'],'postcode': ['contains']}    

class ContactCreate(PermissionMixin, CreateView):
  model = User
  template_name = 'kaucu/base/update.html'
  fields = ['email', 'first_name', 'last_name', 'address1','address2', 'county', 'city', 'postcode', 'phone', 'mobile', 'company']
  def get_success_url(self):
    return reverse('contact:detail', kwargs={'slug':self.object.slug})
  def form_valid(self, form):
    form.instance.creator = self.request.user
    return super().form_valid(form) 
class ContactUpdate(PermissionMixin, UpdateView):
  model = User
  template_name = 'kaucu/base/update.html'
  fields = ['email', 'first_name', 'last_name', 'address1','address2', 'county', 'city', 'postcode', 'phone', 'mobile', 'company']
  queryset = User.objects.contacts()
  def get_success_url(self):
    return reverse('contact:detail', kwargs=self.kwargs)
class ContactDelete(PermissionMixin, DeleteMixin, DeleteView):
  model = User
  responder_redirect_kwargs = {'path':'contact:list'}
class ContactDetail(PermissionMixin, DetailView):
  model = User
  #Setting this template here, becuase model is User but we need to use contact template
  template_name = 'kaucu/contact_detail.html'
  queryset = User.objects.contact_sales()
class ContactList(PermissionMixin, FilterMixin, ListView):
  model = User  
  #Setting this template here, becuase model is User but we need to use contact template
  template_name = 'kaucu/contact_list.html'
  def get_queryset(self):
    queryset = User.objects.restrict_creator(self.request.user).contacts().with_related().order_by(self.ordering)
    self.filter = ContactFilter(self.request.GET, queryset=queryset)
    return self.filter.qs 


class ContactSearch():
  def search(request, query):
    users = User.objects.search_contacts(query)
    return JsonResponse(list(users), safe=False)



class ContactChildUpdate(PermissionMixin, UpdateView):
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    breadcrumbs = []
    breadcrumbs.append((reverse('contact:list'), 'Contacts'))
    breadcrumbs.append((reverse('contact:detail', kwargs={'slug':self.object.user.slug}), self.object.user))
    breadcrumbs.append((reverse('sale:detail', kwargs=self.kwargs), self.object))
    context['breadcrumbs'] = breadcrumbs      
    return context 
class ContactChildDetail(PermissionMixin, DetailView):
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    breadcrumbs = []
    breadcrumbs.append((reverse('contact:list'), 'Contacts'))
    breadcrumbs.append((reverse('contact:detail', kwargs={'slug':self.object.user.slug}), self.object.user))
    context['breadcrumbs'] = breadcrumbs 
    return context  
class ContactChildCreate(PermissionMixin, CreateView):
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    slug = self.kwargs.get('slug')
    if slug is not None: 
      user = User.objects.get(slug=slug)    
      breadcrumbs = []
      breadcrumbs.append((reverse('contact:list'), 'Contacts'))
      breadcrumbs.append((reverse('contact:detail', kwargs=self.kwargs), user))
      context['breadcrumbs'] = breadcrumbs      
    return context
  def form_valid(self, form):
    ## When saving (new) assign the parent object 
    if 'slug' in self.kwargs:
      form.instance.user = User.objects.get(slug=self.kwargs.get('slug'))
    form.instance.creator = self.request.user
    return super().form_valid(form) 
  def get_success_url(self):
    #override/edit this when you create child that does not need to land back to sale_detail
    return reverse('sale:detail', kwargs={'slug':self.object.slug})

class ContactChildDelete(PermissionMixin, DeleteMixin, DeleteView):
  responder_redirect_kwargs = {'path':'contact:detail'}
  def get_success_url(self):
    self.responder_redirect_kwargs['slug'] = self.object.user.slug
    return super().get_success_url()

kaucu/views/dashboard.py
from django.shortcuts import render
from django.views.generic.base import View
from django.forms.utils import ErrorList
from kaucu.models import Supplier, Sale, User

from datetime import date
import dateutil.relativedelta
from django.core.serializers.json import DjangoJSONEncoder
import json
import operator
from kaucu.mixins import *

class DivErrorList(ErrorList):
  def __str__(self):
    return self.as_divs()
  def as_divs(self):
    return '<p>'

class Dashboard(AuthAccessMixin, View):
    date_labels = None
    user_monthly_margins = None
    user_monthly_margins_agg = None
    today = date.today()
    def get(self, request, *args, **kwargs):      
      #Supplier.objects.update_all_supplier_ex_rates()
      
      #Chart Data
      self.date_labels = self.monthly_labels(12)
      self.user_monthly_margins = User.objects.monthly_margins(self.date_labels)
      self.user_monthly_margins_agg = self.user_monthly_margins.monthly_margins_agg(self.date_labels)
      max_agg = max(self.user_monthly_margins_agg.items(), key=operator.itemgetter(1))[1]

      #Chart will display (1) Total monthly margins of all users (2) Total monthly margins of each users
      chart_data = []
      margins_agg = self.create_margins_agg()
      chart_data.append(margins_agg[0])
      chart_data.extend(self.create_margins())

      response = {}
      response['chart_labels'] = json.dumps([i.strftime('%b-%y') for i in self.date_labels], cls=DjangoJSONEncoder)
      response['chart_data'] = json.dumps(list(chart_data), cls=DjangoJSONEncoder)
      response['current_month_total'] = self.user_monthly_margins_agg[self.today.strftime('%m-%Y')+'__sum']
      response['current_month'] = self.today.strftime('%b-%y')
      response['current_year'] = self.today.strftime('%Y')
      response['current_year_total'] = margins_agg[1]
      response['max_agg'] = max_agg

      return render(request, 'kaucu/dashboard.html',response)

    def create_margins_agg(self):
      chart_data_agg = {}
      chart_data_agg['data'] = []
      year_data = []
      for label in self.date_labels:
        value = self.user_monthly_margins_agg[label.strftime('%m-%Y')+'__sum']
        chart_data_agg['data'].append(value)
        if label.year == self.today.year:
          year_data.append(value)
      chart_data_agg['label'] = 'All'
      chart_data_agg['borderColor'] = 'rgba(0, 0, 0, 1)'
      chart_data_agg['pointBackgroundColor'] = 'rgba(0, 0, 0, 1)'
      return (chart_data_agg, sum(year_data))

    def create_margins(self):
      data = []
      for user in self.user_monthly_margins:
        user_chart_data = {}
        user_chart_data['data'] = []
        for label in self.date_labels:
          user_chart_data['data'].append(user[label.strftime('%m-%Y')])
          user_chart_data['label'] = user['first_name']+' '+user['last_name']
          user_chart_data['borderColor'] = user['color']
          user_chart_data['pointBackgroundColor'] = user['color']
          user_chart_data['total'] = 400
        data.append(user_chart_data)
      return data
    
    def monthly_labels(self, number):
      month_labels = []
      for i in range(0, number):
        month = self.today - dateutil.relativedelta.relativedelta(months=i)
        month_labels.append(month)
      return list(reversed(month_labels))

kaucu/templates/kaucu/base/base.html
{% load static %}
{% load myfilters %}
{% firstof object.slug object.pk as slug_or_pk %}
<html class="h-100 mdl-js">

<head>
    <link rel="stylesheet" href="{% static 'css/build.css' %}" type="text/css">
</head>
<script src="{% static 'js/build.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<body class="d-flex flex-column h-100 bg-out">
  {% if request.user.is_authenticated %}
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand mr-4" href="{% url 'dashboard' %}">Travel System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" 
    data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample04">
      <ul class="navbar-nav mr-auto">
        {% with title=request.resolver_match.namespace %}
        <li class="nav-item mr-3 {% if title == '' %}active{% endif %}">
          <a class="nav-link" href="{% url 'dashboard' %}"><i class="fas fa-tachometer-alt"></i> Dashboard <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item mr-3 {% if title == 'sale' %}active{% endif %}">
          <a class="nav-link" href="{% url 'sale:list' %}"><i class="fas fa-chart-line"></i> Sales</a>
        </li>
        <li class="nav-item mr-3 {% if title == 'contact' %}active{% endif %}">
          <a class="nav-link" href="{% url 'contact:list' %}"><i class="fas fa-id-card-alt"></i> Contacts</a>
        </li>
        <li class="nav-item mr-3 {% if title == 'package' %}active{% endif %}">
          <a class="nav-link" href="{% url 'package:list' %}"><i class="fas fa-box-open"></i> Packages</a>
        </li>
        <li class="nav-item mr-3 {% if title == 'payment' %}active{% endif %}">
          <a class="nav-link" href="{% url 'payment:list' %}"><i class="fas fa-money-check"></i> Payments</a>
        </li>
        <li class="nav-item mr-3 {% if title == 'supplier' %}active{% endif %}">
          <a class="nav-link" href="{% url 'supplier:list' %}"><i class="fas fa-layer-group"></i> Suppliers</a>
        </li>
        {% if request.user|has_group:'Admin' or request.user.is_superuser %}
        <li class="nav-item mr-3 {% if title == 'user' %}active{% endif %}">
          <a class="nav-link" href="{% url 'user:list' %}"><i class="fas fa-users"></i> Users</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
      {{request.user}}
      <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="{% url 'user:detail' request.user.slug %}">Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
    </div>
  </nav>
  {% endif %}
  
  {% if request.user.is_authenticated %}
  <div class='container relative mt-3'>
    {% block content %}
    {% endblock %} 
  </div>
  {% else %}
    {% block loginform %}
    {% endblock %} 
  {% endif %}

  <footer class="mt-auto py-3 bg-grey">
  </footer>
  {{ form.media }}
  {% include "kaucu/base/dialog.html" %}
  <script>
      //$( ".row-click td" ).wrapInner( "<span class=\"cancel-click\"></div>" );
      //Cancel click for buttond
      $('.row-click td button').click(function (e) {
        e.stopPropagation();
      });
      //Cancel click for text, so it can be copied
      // $('.row-click .cancel-click').click(function (e) {
      //   e.stopPropagation();
      // });
      $(".row-click").click(function() {
        window.location = $(this).data("href");
      });
    </script>
</body>
</html>

kaucu/templates/kaucu/base/base_dialog.html
{% load static %}
{% load myfilters %}
{% firstof slug pk as slug_or_pk %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'css/build.css' %}" type="text/css">
</head>

<script src="{% static 'js/build.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

{% block content %}
{% endblock %}
{{ form.media }}

<script>
//Sale > Assign Payment, change amound on payment selection
$( "#id_payment" ).change(function() {
  var selectedText = $("#id_payment option:selected").text()
  var res = selectedText.split(":")[1].replace(/\s+/g, '');
  $("#id_amount").val(parseInt(res));
  console.log(res)
});

</script>

</body>
</html>

kaucu/templates/kaucu/base/breadcrumb.html
{% load myfilters %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb bg-none mb-0">
      <!--FOS-->
      <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
      {% if object_list != None %} 
      <li class="breadcrumb-item active">{{request.resolver_match.namespace|maketitle}}s</li>
      {% else %}
        <!--MOS-->
        {% if breadcrumbs %}
          {% for url, title in breadcrumbs %}
            <li class="breadcrumb-item"><a href="{{url}}">{{title}}</a></li>
          {% endfor %}
        {% elif object or form %}
          <li class="breadcrumb-item"><a href="{% url request.resolver_match.namespace|add:':list'%}">{{request.resolver_match.namespace|maketitle}}s</a></li>
          {% if object and form %}
            <li class="breadcrumb-item"><a href="{% url request.resolver_match.namespace|add:':detail' slug_or_pk %}">{{object}}</a></li>
          {% endif %}
        {% endif %}
        <!--EOS-->
        {% if object %}
          {% if form %}
            <li class="breadcrumb-item active">Edit</li> 
            {% include "kaucu/base/menu.html" %} 
          {% else %}
            <li class="breadcrumb-item active">{{object}}</li>  
          {% endif %}
        {% elif form %}
          <li class="breadcrumb-item active">New {{request.resolver_match.namespace|maketitle}}</li>
        {% endif %} 
      {% endif %} 
      
  </ol>
</nav>

kaucu/templates/kaucu/base/buttons.html
{% load myfilters %}

{% with create_perm='kaucu.add_'|add:perm_name %}
{% firstof link_name perm_name as name %}
<div class="col-md-6 mb-2 pr-md-2">
  <a class="row p-4 list-group-item-action cursor align-items-center center bg-in 
    {% if create_perm in perms %} 
      text-primary" 
      {% if handle_dialog %}
        onclick="handleDialog(`
      {% else %}
        href="
      {% endif %}

      {% if slug %}
        {% url name|add:':create' slug %}
      {% elif pk %}
        {% url name|add:':create' pk %}
      {% else %}
        {% url name|add:':create' %}
      {% endif %}

      {% if handle_dialog %}
        `)"
      {% else %}
        "
      {% endif %}

    {% else %}
      disabled" href="#"
    {% endif %}>
    <div class="col-sm-12">+ New {{ name|maketitle }}</div>
  </a>
</div>
{% endwith %}

<div class="{% if has_filter == False %} col-md-6 {% else %} col-md-5  pr-md-2 {% endif %} mb-2">
  <div class="row p-4 align-items-center center bg-in clr-white">
    <div class="col-sm-12 pt-3 pb-2"></div>
  </div>
</div>

kaucu/templates/kaucu/base/buttons_dropdown.html
{% load myfilters %}
<div class="col-md-6 mb-2 pr-md-2">
    <div class="col-sm-12 mb-2 pr-sm-2">
      <div class="row p-4 align-items-center center bg-in text-primary ">
        <div class="col-sm-12">
            <div class="dropdown show">
                <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    + Add {{name|title}}</a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    {% for button in buttons.split %}
                    <a class="dropdown-item
                    {% with create_perm='kaucu.add_'|add:button %}
                      {% if create_perm in perms %} 
                       " href="{% url button|add:':create' slug %}"
                      {% else %}
                       disabled" href="#"
                      {% endif %}
                    {% endwith %}
                    ">{{button|title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
      </div>
    </div>
</div>
<div class="{% if has_filter == False %} col-md-6 {% else %} col-md-5  pr-md-2 {% endif %} mb-2">
  <div class="row p-4 align-items-center center bg-in clr-white">
    <div class="col-sm-12 pt-3 pb-2"></div>
  </div>
</div>

kaucu/templates/kaucu/base/datetimepicker.html
<div class="input-group date" id="{{ widget.datetimepicker_id }}" data-target-input="nearest">
    {% include "django/forms/widgets/input.html" %}
    <div class="input-group-append" data-target="#{{ widget.datetimepicker_id }}" data-toggle="datetimepicker">
      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
    </div>
  </div>
  
<script>
  $(function () {
    $("#{{ widget.datetimepicker_id }}").datetimepicker({
      {% if widget.format == 'DATE' %}
        format: 'DD/MM/YYYY',
      {% else %}
        format: 'DD/MM/YYYY H:M',
      {% endif %}
    });
  });
</script>

kaucu/templates/kaucu/base/responder.html
{% load static %}
{% firstof slug pk as slug_or_pk %}
<script>
  var responderURL = "{{responderURL}}"
  if ( responderURL != ""){
    window.top.location.href = responderURL
  } else {
    console.log("{{slug_or_pk}}")
    window.top.hideDialog()
    window.top.$('#{{slug_or_pk}}').remove();
  }
</script>