kaucu/urls.py
from django.urls import path, include

from kaucu import views
from django.contrib.auth import views as auth_views


user_patterns = ([
    path('', views.UserList.as_view() , name='list'),
    path('<str:slug>/', views.UserDetail.as_view() , name='detail'),
    path('<str:slug>/update', views.UserUpdate.as_view() , name='update'),
    path('<str:slug>/delete', views.UserDelete.as_view() , name='delete'),
    path('create_user', views.UserCreate.as_view() , name='create'),
], 'user')

contact_patterns = ([
    path('', views.ContactList.as_view() , name='list'),
    path('<str:slug>/', views.ContactDetail.as_view() , name='detail'),
    path('<str:slug>/update', views.ContactUpdate.as_view() , name='update'),
    path('<str:slug>/delete', views.ContactDelete.as_view() , name='delete'),
    path('create_contact', views.ContactCreate.as_view() , name='create'),
    path('search/<str:query>', views.ContactSearch.search , name='search'),
], 'contact')

package_patterns = ([
  path('create_package', views.PackageCreate.as_view() , name='create'),
  path('', views.PackageList.as_view() , name='list'),
  path('<int:pk>/', views.PackageDetail.as_view() , name='detail'),
  path('<int:pk>/update', views.PackageUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.PackageDelete.as_view() , name='delete'),
], 'package')

sale_patterns = ([
  path('', views.SaleList.as_view() , name='list'),
  path('<str:slug>/', views.SaleDetail.as_view() , name='detail'),
  path('<str:slug>/payment', views.SaleDetail.as_view() , name='payment'),
  path('<str:slug>/passenger', views.SaleDetail.as_view() , name='passenger'),
  path('<str:slug>/activity', views.SaleDetail.as_view() , name='activity'),

  path('<str:slug>/update', views.SaleUpdate.as_view() , name='update'),
  path('<str:slug>/delete', views.SaleDelete.as_view() , name='delete'),
  path('<str:slug>/create', views.SaleCreate.as_view() , name='create'),
  path('create', views.SaleCreate.as_view() , name='create'),

], 'sale')

hotel_patterns = ([
  path('<str:slug>/create', views.HotelCreate.as_view() , name='create'),
  path('<int:pk>/update', views.HotelUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.HotelDelete.as_view() , name='delete'),
], 'hotel')

flight_patterns = ([
  path('<str:slug>/create', views.FlightCreate.as_view() , name='create'),
  path('<int:pk>/update', views.FlightUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.FlightDelete.as_view() , name='delete'),
], 'flight')

transfer_patterns = ([
  path('<str:slug>/create', views.TransferCreate.as_view() , name='create'),
  path('<int:pk>/update', views.TransferUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.TransferDelete.as_view() , name='delete'),
], 'transfer')


passenger_patterns = ([
  path('<int:pk>/', views.PassengerDelete.as_view() , name='detail'),
  path('<str:slug>/create', views.PassengerCreate.as_view() , name='create'),
  path('<int:pk>/update', views.PassengerUpdate.as_view() , name='update'),
  path('<int:pk>/delete', views.PassengerDelete.as_view() , name='delete'),
], 'passenger')


payment_patterns = ([
    path('', views.PaymentList.as_view() , name='list'),
    path('<str:slug>/delete', views.PaymentDelete.as_view() , name='delete'),
    path('create_payment', views.PaymentCreate.as_view() , name='create'),
], 'payment')

sale_payment = ([
    path('<str:slug>/<int:pk>/delete', views.Sale_PaymentDelete.as_view() , name='delete'),
    path('<str:slug>/create', views.Sale_PaymentCreate.as_view() , name='create'),
], 'sale_payment')

supplier_payment = ([
    path('<int:pk>/delete', views.Supplier_PaymentDelete.as_view() , name='delete'),
    path('<int:pk>/create', views.Supplier_PaymentCreate.as_view() , name='create'),
], 'supplier_payment')

supplier_patterns = ([
    path('', views.SupplierList.as_view() , name='list'),
    path('<int:pk>/', views.SupplierDetail.as_view() , name='detail'),
    path('<int:pk>/update', views.SupplierUpdate.as_view() , name='update'),
    path('<int:pk>/delete', views.SupplierDelete.as_view() , name='delete'),
    path('create_supplier', views.SupplierCreate.as_view() , name='create'),
], 'supplier')

responder_patterns = ([
    path('<int:pk>/respond', views.Responder.as_view(), name='respond'),
    path('<str:slug>/respond', views.Responder.as_view(), name='respond'),
    path('<str:path>/redirect', views.ResponderRedirect.as_view(), name='redirect'),
    path('<str:slug>/<str:path>/redirect_slug', views.ResponderRedirectArgs.as_view(), name='redirect_slug'),
    path('<int:pk>/<str:path>/redirect_pk', views.ResponderRedirectArgs.as_view(), name='redirect_pk'),

], 'responder')

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('responder/', include(responder_patterns)),
    path('contact/', include(contact_patterns)),
    path('user/', include(user_patterns)),

    path('package/', include(package_patterns)),
    path('sale/', include(sale_patterns)),
    path('hotel/', include(hotel_patterns)),
    path('flight/', include(flight_patterns)),
    path('transfer/', include(transfer_patterns)),
    path('payment/', include(payment_patterns)),
    path('sale_payment/', include(sale_payment)),
    path('supplier_payment/', include(supplier_payment)),
    path('supplier/', include(supplier_patterns)),

    path('passenger/', include(passenger_patterns)),
]

kaucudjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('kaucu.urls')),
    path('admin/', admin.site.urls),
]

kaucu/models/package.py
from django.db import models
from .user import User

class Package(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_packages')

  package = models.CharField(max_length=100)  
  allow_custom_services = models.BooleanField(default=True)

  def __str__(self):
    return u'{0}'.format(self.package)

kaucu/models/passenger.py
from django.db import models
from kaucu.helpers import *
from django.db.models import Sum, F    
from django.db.models.functions import Coalesce
from django import forms
from .user import User
from .sale import Sale
from model_utils import Choices

class PassengerQuerySet(models.QuerySet):
  pass
class Passenger(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  sale = models.ForeignKey(Sale, on_delete=models.CASCADE)

  first_name = models.CharField(max_length=30)
  last_name = models.CharField(max_length=150)
  dob = models.DateField(null=True, blank=True)
  nationality = models.CharField(max_length=150, null=True, blank=True)
  birth_place = models.CharField(max_length=150, null=True, blank=True)
  passport_number = models.CharField(max_length=50, null=True, blank=True)
  passport_issue_country = models.CharField(max_length=100, null=True, blank=True)
  passport_expiry = models.DateField(null=True, blank=True)
  passport_issue = models.DateField(null=True, blank=True)
  contact_number = models.IntegerField(null=True, blank=True)
  
  TITLE = Choices(('Mr', 'mr', 'Mr'),('Mrs', 'mrs', 'Mrs'),('Miss', 'miss', 'Miss'),('Master', 'master', 'Master'), ('Dr', 'dr', 'Dr'))
  GENDER = Choices(('M', 'male', 'Male'),('F', 'female', 'Female'))
  title = models.CharField(max_length=6, choices=TITLE)
  gender = models.CharField(max_length=1, choices=GENDER)
  
  objects = PassengerQuerySet.as_manager()

  def __str__(self):
    return self.first_name+' '+self.last_name

kaucu/models/sale.py
from django.db import models
from django.db.models import Sum, F, Aggregate, Count, OuterRef, Subquery, Value, Min, Case, When

from .user import User
from .package import *
from kaucu.helpers import *
from django.db.models.functions import Coalesce
from django.db.models import *

from model_utils import Choices
from datetime import date

class SaleQuerySet(models.QuerySet):
  def restrict_creator(self, user):
    #If user is Admin or SuperAdmin show all sale objects, or else only show the created by user
    if user.groups.filter(name='Admin').exists() or user.is_superuser:
      return self
    else:
      return self.filter(creator=user)
  def with_related(self):
    return self.select_related('user', 'package', 'creator')
  def with_prefetch_related(self):
    return self.with_related().prefetch_related('hotel_set', 'flight_set', 'transfer_set', 'sale_payment_set', 'passenger_set')


class Sale(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_sales')
  slug = models.SlugField(unique=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  package = models.ForeignKey(Package, on_delete=models.CASCADE)

  price = models.DecimalField(default=0, decimal_places=2, max_digits=8)
  cost = models.DecimalField(default=0, decimal_places=2, max_digits=8)
  confirmed_date = models.DateField(null=True)
  adult = models.IntegerField(default=0)
  child = models.IntegerField(default=0)
  infant = models.IntegerField(default=0)

  STATUS = Choices(('New', 'new', 'New'),('Negotiating', 'negotiating', 'Negotiating'),
  ('Payment Pending', 'pending', 'Payment Pending'), ('Confirmed', 'confirmed', 'Confirmed'), ('Cancelled', 'cancelled', 'Cancelled'))
  status = models.CharField(max_length=20, choices=STATUS)
  
  objects = SaleQuerySet.as_manager()

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = "S"+str(Helpers.randomInt(6))
    super().save(*args, **kwargs)
  def __str__(self):
    return u'{0}'.format('Sale '+self.slug)
  
  def recalculate_cost(self):
    from kaucu.models import Hotel, Flight, Transfer, Supplier
    self.cost = 0
    service_classes = [Hotel,Flight,Transfer]
    for service_class in service_classes:
      #Get all of the service type for this sale
      services = service_class.objects.filter(sale=self)
      self.cost += services.aggregate(t=Coalesce(Sum(F('cost')/F('currency_rate')),0))['t']
    self.save(update_fields=['cost'])

  def update_status(self):
    from kaucu.models import Sale_Payment
    ##Confirmed date = Date of first payment
    confirmed_date = Sale_Payment.objects.filter(sale=self).aggregate(date=Min('payment__paid_date'))['date']
    if confirmed_date:
      if self.status != self.STATUS.confirmed:
        self.status = self.STATUS.confirmed
      self.confirmed_date = confirmed_date
      self.save(update_fields=['status','confirmed_date'])
    else:
      self.status = self.STATUS.pending
      self.confirmed_date = None
      self.save(update_fields=['status','confirmed_date'])

  def get_balance_sheet(self):    
    payment_in = Case(When(payment__direction='IN', then='amount'), default=0)
    payment_out = Case(When(payment__direction='OUT', then='amount'), default=0)
    sale_payments = self.sale_payment_set.all().values(paid_date=F('payment__paid_date'), out_payment=payment_out, in_payment=payment_in, payment_slug=F('payment__slug'), pk=F('pk'))
    return sale_payments.order_by('-paid_date')




    #services.update(currency_rate=Subquery(Supplier.objects.filter(id=OuterRef('supplier_id')).values('currency_rate')))   ##update rate if needed
    
    # hotel_total = Hotel.objects.filter(sale=self).aggregate(t=Coalesce(Sum(F('cost')/F('currency_rate')),0))
    # flight_total = Flight.objects.filter(sale=self).aggregate(t=Coalesce(Sum(F('cost')/F('currency_rate')),0))
    # transfer_total = Transfer.objects.filter(sale=self).aggregate(t=Coalesce(Sum(F('cost')/F('currency_rate')),0))
    # self.cost = hotel_total['t'] + flight_total['t'] + transfer_total['t']
  
  # def monthly_margin_totals(self, date_labels):
  #   to_sum = Sum(F('price')-F('cost'))
  #   months = {}
  #   for date in date_labels:
  #     case = Sum(Case(When(confirmed_date__month=date.month, confirmed_date__year=date.year, then=F('price')-F('cost')), default=0))
  #     months[date.strftime('%m/%Y')] = case
  #   return self.values('creator_id').annotate(**months)

kaucu/models/supplier.py
from django.db import models
from kaucu.api import CurrencyLayer
import datetime
from django.utils import timezone
from django.db.models import Sum, F, Aggregate, Count, OuterRef, Subquery, Value, CharField, IntegerField, When, DecimalField, Case, Q 
from django.db.models.functions import Coalesce

from .user import User

class SupplierQuerySet(models.QuerySet):
  def services_prefetch(self):
    return self.prefetch_related('hotel_set', 'flight_set', 'transfer_set', 'supplier_payment_set')
  def update_all_supplier_ex_rates(self):
    rates = {}
    now = timezone.now()
    for supplier in self.all():
      if now.date() > supplier.last_edit.date():
        if supplier.currency not in rates:
          new_rate = CurrencyLayer().exchangeRate(supplier.currency)
          if new_rate == None:  return 
          rates[supplier.currency] = new_rate
          supplier.currency_rate = rates[supplier.currency]
        else:
          supplier.currency_rate = rates[supplier.currency]
        supplier.save()

class Supplier(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  last_edit = models.DateTimeField(auto_now=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_suppliers')

  supplier = models.CharField(max_length=100)
  currency = models.CharField(max_length=3)
  currency_rate = models.DecimalField(default=1, decimal_places=2, max_digits=8)
  
  objects = SupplierQuerySet.as_manager()
  
  def save(self, *args, **kwargs):
    self.currency_rate = CurrencyLayer().exchangeRate(self.currency)
    super().save(*args, **kwargs)

  def __str__(self):
    return u'{0}'.format(self.supplier + ' ('+str(self.currency)+')')

  def get_balance_sheet(self):
    hotel_val = Value('Hotel', CharField())
    flight_val = Value('Flight', CharField())
    transfer_val = Value('Transfer', CharField())
    blank_val = Value('', CharField())
    #sqlite not accepting DecimalField, works with IntegerField for some reason
    zero_val = Value(0, IntegerField())
    
    payment_in = Case(When(payment__direction='IN', then='amount'), default=0)
    payment_out = Case(When(payment__direction='OUT', then='amount'), default=0)    
    confirmed = Q(sale__status='Confirmed')

    supplier_payments = self.supplier_payment_set.all().values(paid_date=F('payment__paid_date'), out_payment=payment_out, in_payment=payment_in, package=blank_val, slug=F('payment__slug'), pk=F('pk'), service=blank_val)
    hotels = self.hotel_set.filter(confirmed).values(paid_date=F('sale__confirmed_date'), out_payment=zero_val, in_payment=F('cost') , package=F('sale__package__package'), slug=F('sale__slug'), pk=F('pk'), service=hotel_val)
    flights = self.flight_set.filter(confirmed).values(paid_date=F('sale__confirmed_date'), out_payment=zero_val, in_payment=F('cost'), package=F('sale__package__package'), slug=F('sale__slug'), pk=F('pk'), service=flight_val)
    transfer = self.transfer_set.filter(confirmed).values(paid_date=F('sale__confirmed_date'), out_payment=zero_val, in_payment=F('cost'), package=F('sale__package__package'), slug=F('sale__slug'), pk=F('pk'), service=transfer_val)

    return supplier_payments.union(hotels, flights, transfer).order_by('-paid_date')

kaucu/views/flight.py
from django.urls import reverse
from django import forms
from kaucu.widgets import DateTimePickerInput

from kaucu.models import Flight
from .sale import SaleChildCreate, SaleChildUpdate, SaleChildDelete
from django.conf import settings

class FlightForm(forms.ModelForm):
  cost = forms.IntegerField(min_value=0)
  adult = forms.IntegerField(min_value=0)
  child = forms.IntegerField(min_value=0)
  infant = forms.IntegerField(min_value=0)
  
  departure_time = forms.DateTimeField(input_formats=settings.DATETIME_INPUT_FORMATS, widget=DateTimePickerInput())
  arrival_time = forms.DateTimeField(input_formats=settings.DATETIME_INPUT_FORMATS, widget=DateTimePickerInput())
  departure_airport = forms.CharField(widget=forms.widgets.Select(attrs={'data-live-search':'true', 'data-live-search-placeholder':'Search by Airport Code or Name'}))
  arrival_airport = forms.CharField(widget=forms.widgets.Select(attrs={'data-live-search':'true', 'data-live-search-placeholder':'Search by Airport Code or Name'}))
  airline = forms.CharField(widget=forms.widgets.Select(attrs={'data-live-search':'true', 'data-live-search-placeholder':'Search by Airline'}))

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    if self.instance.departure_airport:
      self.fields['departure_airport'].widget.choices = [(self.instance.departure_airport, self.instance.departure_airport)]
    if self.instance.arrival_airport:
      self.fields['arrival_airport'].widget.choices = [(self.instance.arrival_airport, self.instance.arrival_airport)]
    if self.instance.airline:
      self.fields['airline'].widget.choices = [(self.instance.airline, self.instance.airline)]

  class Meta:
    model = Flight
    fields = ['supplier', 'seat_class', 'flight_no','airline', 'departure_airport', 'departure_time', 'arrival_airport', 'arrival_time', 'adult', 'child', 'infant', 'cost']

class FlightCreate(SaleChildCreate):
  template_name = 'kaucu/base/update.html'
  form_class = FlightForm

class FlightUpdate(SaleChildUpdate):
  template_name = 'kaucu/base/update.html'
  form_class = FlightForm
  model = Flight
class FlightDelete(SaleChildDelete):
  model = Flight

kaucu/templates/kaucu/contact_detail.html
{% extends 'kaucu/base/base.html' %}
{% load myfilters %}
{% block content %}
{% include "kaucu/base/title.html" %}
{% include "kaucu/base/breadcrumb.html" %}

{% if perms.kaucu.change_user %}
<a class="bread-icon clr-m" href="{% url request.resolver_match.namespace|add:':update' slug_or_pk %}">
    <i class="far fa-edit"></i>
</a>  
{% endif %}   
<div class="row">
    <div class="col-lg-12 bg-in py-4 mb-2">
        <div class="row">
            <div class="col-lg-6">
              <div class="row">
                <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Email</div>
                <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.email }}</div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="row">
                <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Creator</div>
                <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{object.creator|default_if_none:""}}</div>
              </div>
            </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">First Name</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.first_name }}</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Last Name</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.last_name }}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Adress 1</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.address1|default_if_none:"" }}</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Address 2</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.address2|default_if_none:"" }}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">County</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.county|default_if_none:"" }}</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">City</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.city|default_if_none:"" }}</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Postcode</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.postcode|default_if_none:"" }}</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Company</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.company|default_if_none:"" }}</div>
            </div>
          </div>
        </div>
      </div>
</div>

<div class="row">
  {% with perm_name='sale' slug=object.slug has_filter=False %}
    {% include "kaucu/base/buttons.html" %}
  {% endwith %}
</div>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="sales-tab" data-toggle="tab" href="#sales" role="tab" aria-controls="sales"
      aria-selected="true">Sales</a>
  </li>
</ul>
<div class="tab-content mt-2" id="myTabContent">
  <div class="tab-pane fade show active" id="sales" role="tabpanel" aria-labelledby="sales-tab">    
    <div class="table-responsive-lg bg-in mb-2">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Package</th>
            <th scope="col">Price</th>
            <th scope="col">Cost</th>
            <th scope="col">A</th>
            <th scope="col">C</th>
            <th scope="col">I</th>
            <th scope="col">Status</th>
            <th scope="col">Created</th>
            <th scope="col">Creator</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for item in object.sale_set.all %}
          <tr class="row-click cursor" data-href="{% url 'sale:detail' item.slug %}">
            <td>{{ item.slug }}</td>
            <td>{{ item.package }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.cost }}</td>
            <td>{{ item.adult }}</td>
            <td>{{ item.child }}</td>
            <td>{{ item.infant }}</td>
            <td class="clr-white center" scope="row"><div class="py-1 px-1 rounded {{item.status|makeClass }}-status">{{ item.status }} </div></td>
            <td>{{ item.created|date:"d/m/y H:i" }}</td>
            <td>{{ item.creator }}</td>
            <td>
              <button class="close text-danger" onclick="handleDialog(`{% url 'sale:delete' item.slug %}`)" type="button"  aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </td>
          
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

kaucu/templates/kaucu/contact_list.html
{% extends 'kaucu/base/base.html' %}
{% block content %}
{% include "kaucu/base/title.html" %}
{% include "kaucu/base/breadcrumb.html" %}
<div class="right-icon"><i class="fas fa-id-card-alt"></i></div>
<div class="row">
  {% with perm_name='user' link_name='contact' %}
    {% include "kaucu/base/buttons.html" %}
  {% endwith %}
  {% include "kaucu/base/filter_form.html" %}
</div>
<div class="table-responsive-lg bg-in mb-2">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Created</th>
        <th scope="col">Creator</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr class="row-click cursor" data-href="{% url 'contact:detail' object.slug %}">
        <td>{{ object.slug }}</td>
        <td>{{ object.first_name }}</td>
        <td>{{ object.last_name }}</td>
        <td>{{ object.email }}</td>
        <td>{{ object.created|date:"d/m/y H:i" }}</td>
        <td>{{ object.creator }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% include "kaucu/base/paginate.html" %}
{% endblock %}

kaucu/templates/kaucu/package_detail.html
{% extends 'kaucu/base/base.html' %}
{% block content %}
{% include "kaucu/base/title.html" %}
{% include "kaucu/base/breadcrumb.html" %}
{% if perms.kaucu.change_package %}
<a class="bread-icon clr-m" href="{% url request.resolver_match.namespace|add:':update' slug_or_pk %}">
    <i class="far fa-edit"></i>
</a>  
{% endif %}   

<div class="row">
  <div class="col-lg-12 bg-in py-4 mb-2">
      <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Package</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.package }}</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Creator</div>
              <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{ object.creator }}</div>
            </div>
          </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="row">
            <div class="col-sm-4 col-lg-4 mb-sm-3 pl-4">Allow Custom Services</div>
            <div class="col-sm-8 col-lg-8 mb-3 pr-4 pl-4 pl-sm-0">{{object.allow_custom_services}}</div>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}